export const Theme = {
  light: {
    color: {
      primaryMain: "#36662F",
      primaryLight: "#5FB54C",
      primaryDark: "#2E432B",
      backgroundPaper: "#FFFFFF",
      backgroundDefaultOpacity: "rgba(235, 235, 235, 0.8)",
      backgroundDefault: "#EBEBEB",
      primaryContrastText: "#000",
      textPrimary: "#0B0E10",
      textSecondary: "#303030",
    },
    size: {
      xs: "0.75rem",
      sm: "0.875rem",
      md: "1rem",
      lg: "1.25rem",
      xl: "1.5rem",
    },
    weight: {
      light: "300",
      regular: "400",
      medium: "500",
      semiBold: "600",
      bold: "700",
      extraBold: "800",
      black: "900",
    },
    spacing: {
      xxs: "4px",
      xs: "8px",
      sm: "12px",
      md: "16px",
      lg: "20px",
      xl: "24px",
      xxl: "32px",
      xxxl: "60px",
    },
    radius: {
      xs: "6px",
      sm: "12px",
      md: "18px",
      lg: "100px",
    },
  },

  dark: {
    color: {
      primaryMain: "#5FB54C",
      primaryLight: "#75FA4E",
      primaryDark: "#36662F",
      primaryContrastText: "#FFFFFF",
      backgroundPaper: "#232122",
      backgroundDefaultOpacity: "rgba(48, 48, 48, 0.8)",
      backgroundDefault: "#303030",
      textPrimary: "#FFFFFF",
      textSecondary: "#EBEBEB",
    },
    size: {
      xs: "0.75rem",
      sm: "0.875rem",
      md: "1rem",
      lg: "1.25rem",
      xl: "1.5rem",
    },
    weight: {
      light: "300",
      regular: "400",
      medium: "500",
      semiBold: "600",
      bold: "700",
      extraBold: "800",
      black: "900",
    },
    spacing: {
      xxs: "4px",
      xs: "8px",
      sm: "12px",
      md: "16px",
      lg: "20px",
      xl: "24px",
      xxl: "32px",
      xxxl: "60px",
    },
    radius: {
      xs: "6px",
      sm: "12px",
      md: "18px",
      lg: "100px",
    },
  },
};
